In [4]:
import os
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
%matplotlib inline

In [7]:
file_path = "./Robinhood_Report_*"
files_with_data = glob.glob(os.path.join(file_path+".csv"))
data = pd.concat((pd.read_csv(f, header=None, names=range(10), low_memory=False) for f in files_with_data), sort=False)
data.head()

,0,1,2,3,4,5,6,7,8,9
0,Activity Date,Process Date,Settle Date,Instrument,Description,Trans Code,Quantity,Price,Amount,NaN
1,6/14/2023,6/14/2023,6/16/2023,SDIV,Global X SuperDividend ETF\nCUSIP: 37960A669\n...,Buy,0.846906,$22.47,($19.03),NaN
2,6/14/2023,6/14/2023,6/16/2023,TECB,iShares U.S. Tech Breakthrough Multisector\nCU...,Buy,0.007442,$37.62,($0.28),NaN
3,6/13/2023,6/13/2023,6/13/2023,SDIV,Cash Div: R/D 2023-06-06 P/D 2023-06-13 - 88.5...,CDIV,NaN,NaN,$19.03,NaN
4,6/13/2023,6/13/2023,6/13/2023,TECB,Cash Div: R/D 2023-06-08 P/D 2023-06-13 - 13.8...,CDIV,NaN,NaN,$0.28,NaN